server:
  port: 8200
spring:
  application:
    name: microservice-consumer-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: false
#  #feign 对hytrix的支持
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000