spring:
  application:
    name: config-client
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
server:
  port: 13001
#开端点，也就是暴露接口
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
